package Unit_03;
import java.util.Scanner;

class Test{
	int a=10;
	
		void basicException(){
			try{
				int b = a/0;
				System.out.println("B = "+b);
			}
			catch(Exception e){
				System.out.println(e.getMessage());
			}
		}
		
		void multipleCatch(){
			try{
				int b=a/0;
				System.out.println("B = "+b);
			}
			
			catch(ArithmeticException e){
				System.out.println("First catch block");
				System.out.println(e.getMessage());
			}
			
			catch(Exception e){
				System.out.println("Second catch block");
				System.out.println(e.getMessage());
			}
		}
		
		void inputMismatchException(){
			Scanner sc = new Scanner(System.in);
			System.out.println("Enter value: ");
			
			try{
				int c = sc.nextInt();
			}
			catch(Exception e){
				System.out.println(e+ " Resolved");
			}
		}
		
		void stackOverFlowError(){
			int c=1;
			
			try{
				if(c>0)
					stackOverFlowError();
			}
			catch(Exception e){
				System.out.println(e.getMessage());
			}
			finally{				
				System.out.println("Other code execution");
			}
		}
		
		void useOfThrow(int age) throws Exception{
			if(age<18)
				throw new Exception();
			else
				System.out.println("Age: "+age);
		}
}

public class P14_ExceptionHandling {

	public static void main(String[] args) {
		Test obj = new Test();
		//obj.basicException();
		//obj.multipleCatch();
		//obj.inputMismatchException();
		obj.stackOverFlowError();
		
//		try {
//			obj.useOfThrow(15);
//		} catch (Exception e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		}
	}
}
